### ISSUE TITLE
Sort all children by tag name

### ISSUE THREAD

**Issue by ca-d** [ca-d/scl-diff-prototype#1]
Sort added and removed elements together with changed elements

**Comment by ca-d** [comment]
Try sorting elements by identity within tag names and get feedback on that

**Comment by danyill** [comment]
I think for some elements the user expects them not to be sorted -- e.g. the DataSet FCDA elements.

Perhaps at each layer in the hierarchy the user could have the option to have either the document order or a sort by identity string?

**Comment by ca-d** [comment]
Surprisingly, document order would be hard to do for us. We currently lose that information upon translating the file to our internal format: Dependencies and children of nodes in our tree are all thrown together into a single **set**, i.e. the order and multiplicity of those elements are gone. This has algorithmic advantages for us, but means that any order we show must be strictly arbitrary: We can choose any order we like, but we must choose some order.

To be clear: Where children's order or multiplicity actually has some *meaning* for the configuration in question, we will of course want to make an exception and store a list of children rather than a set. In these cases, we will want to show exactly those elements' order and multiplicities in the UI, but only there.

**Comment by danyill** [comment]
Well in that case sorting by identity string works for me, thanks
